version: '3'

tasks:
  clean:
    desc: Clean generated artifacts
    summary: |
      Clean generated artifacts via latexmk.
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - latexmk -C

  pdf:
    desc: Generate PDF
    summary: |
      Generate PDF via latexmk.
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - latexmk --pdf *.tex
